import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  // https://www.youtube.com/watch?v=Cn8Y9zmnbDM&list=PLFGFKs8nQ3EbG-ykV8xc1mBt99sqq2Ssx&index=2 => Tutorial playlist
  // https://github.com/dijonmusters/e-commerce-in-25-days => Tutorial repository

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>E-commerce app</h1>
      </main>
    </div>
  );
}
